ALTER TYPE "BoardType" ADD VALUE IF NOT EXISTS 'IB';
ALTER TYPE "BoardType" ADD VALUE IF NOT EXISTS 'IGCSE';
ALTER TYPE "BoardType" ADD VALUE IF NOT EXISTS 'NIOS';
ALTER TYPE "BoardType" ADD VALUE IF NOT EXISTS 'STATE_BOARD';
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "stateBoardName" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "earlyChildhoodFee" INTEGER;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "socialLinks" JSONB;
