ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "languagesOffered" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "recognitionNumber" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "affiliatedSince" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "uniformPolicy" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "canteenAvailable" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "facilityCustomGroups" JSONB;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "sportsCustomGroups" JSONB;
